#!/bin/bash

#Only if var log is mounted a tmpfs.
if mount | grep "/var/log type tmpfs"; then

if [ ! -d /var/log/apache];
then
mkdir /var/log/apache
touch /var/log/apache/access.log
chmod 700 /var/log/apache/access.log

fi

if [ ! -d /var/log/apache2];
then
mkdir /var/log/apache2
touch /var/log/apach2e/access.log
chmod 700 /var/log/apache2/access.log

fi


fi
